Changes to be committed: 	modified:   src/Lib.hs
Fix:
/media/psf/Home/prog/Haskell/dividend-portfolio/src/Lib.hs:25:10: error: [GHC-83865]
    • Couldn't match type ‘Char’ with ‘[Char]’
      Expected: [String] -> [Char]
        Actual: [Char] -> [Char]
    • In the first argument of ‘(>>>)’, namely ‘intersperse ','’
      In the first argument of ‘arr’, namely
        ‘(intersperse ',' >>> concat)’
      In the second argument of ‘(>>>)’, namely
        ‘arr (intersperse ',' >>> concat)’
   |
25 |     arr (intersperse ',' >>> concat)
   |          ^^^^^^^^^^^^^^^