Changes to be committed: 	modified:   src/Lib.hs
/media/psf/Home/prog/Haskell/dividend-portfolio/src/Lib.hs:19:15: error: [GHC-83865]
    • Couldn't match type: Data.Tree.NTree.TypeDefs.NTree XNode
                     with: [Char]
      Expected: IOSLA (XIOState ()) String XmlTree
        Actual: IOStateArrow () XmlTree XmlTree
    • In the second argument of ‘(>>>)’, namely
        ‘writeDocument [withOutputEncoding utf8] outputFile’
      In the second argument of ‘(>>>)’, namely
        ‘processXmlToCsv
           >>> writeDocument [withOutputEncoding utf8] outputFile’
      In the first argument of ‘runX’, namely
        ‘(readDocument [withValidate no] inputFile
            >>>
              processXmlToCsv
                >>> writeDocument [withOutputEncoding utf8] outputFile)’
   |
19 |           >>> writeDocument [withOutputEncoding utf8] outputFile)